name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
      - dev-new
      - '*'
  pull_request:
    branches:
      - main
      - dev-new

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew clean build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Run tests with Gradle
        run: ./gradlew test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Set branch name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - name: Update Render service branch
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            SERVICE_ID=${{ secrets.RENDER_SERVICE_ID_MAIN }}
          elif [ "${{ github.ref_name }}" == "dev-new" ]; then
            SERVICE_ID=${{ secrets.RENDER_SERVICE_ID_DEV }}
          else
            SERVICE_ID=${{ secrets.RENDER_SERVICE_ID_FEATURE }}
          fi

          curl --request PATCH \
            --url https://api.render.com/v1/services/$SERVICE_ID \
            --header 'accept: application/json' \
            --header 'content-type: application/json' \
            --header "Authorization: Bearer $RENDER_API_KEY" \
            --data '{"branch":"${{ github.ref_name }}"}'

      - uses: actions/checkout@v3
      - name: Deploy to Render (Main)
        if: github.ref_name == 'main'
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID_MAIN }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true
          branch: ${{ github.ref_name }}
      - name: Deploy to Render (Dev)
        if: github.ref_name == 'dev-new'
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID_DEV }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true
          branch: ${{ github.ref_name }}
      - name: Deploy to Render (Feature)
        if: github.ref_name != 'main' && github.ref_name != 'dev-new'
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID_FEATURE }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true
          branch: ${{ github.ref_name }}
